In [1]:
my_list = [1,2,3,4]

In [2]:
import numpy as np

In [3]:
np.array([my_list])

array([[1, 2, 3, 4]])

In [4]:
arr = np.array([my_list])

In [5]:
arr

array([[1, 2, 3, 4]])

# 2-D matrix

In [6]:
my_matrices = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
my_matrices

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(my_matrices)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Range and Arange

In [9]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.ones(3)

array([1., 1., 1.])

In [15]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
np.arange(0,5,10)

array([0])

In [17]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [18]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
np.random.rand(5)

array([0.32363672, 0.49724458, 0.6610009 , 0.33199769, 0.96009698])

In [20]:
np.random.rand(5,5)

array([[0.07229055, 0.7351062 , 0.57489964, 0.11228335, 0.30321368],
       [0.34390436, 0.7123063 , 0.19761571, 0.11719514, 0.11437432],
       [0.61599694, 0.24591654, 0.8272335 , 0.15510243, 0.21869657],
       [0.30763027, 0.80173442, 0.50003552, 0.91977113, 0.33147093],
       [0.81531827, 0.64955031, 0.13713686, 0.85110792, 0.23536643]])

In [21]:
np.random.randn(2)

array([-0.48885649, -0.99289674])

In [22]:
np.random.randn(2,2)

array([[-0.1154304 , -1.54383937],
       [ 1.31250481,  1.66679603]])

# Random Integer Range

In [23]:
np.random.randint(0,100,10)

array([ 3, 97, 71, 66, 80, 94, 74, 81,  4, 33])

# Methods in Array

In [24]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [25]:
rand_arr = np.random.randint(0,50,10)
rand_arr

array([29, 46, 41,  3, 38, 26, 42, 34, 23,  5])

In [26]:
arr.reshape(5,5)
# It will give error if you can't fill up matrix correctly.

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

# other methods

In [27]:
rand_arr

array([29, 46, 41,  3, 38, 26, 42, 34, 23,  5])

In [28]:
# max min values will be as per the random array values

In [29]:
rand_arr.max()

46

In [30]:
rand_arr.min()

3

In [31]:
rand_arr.argmax()
# This will give max values "index"

1

In [32]:
rand_arr.argmin()

3

In [33]:
arr.shape

(25,)

In [34]:
arr = arr.reshape(5,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [35]:
# Now
arr.shape

(5, 5)

In [36]:
arr.dtype

dtype('int32')

In [37]:
rand_arr.dtype

dtype('int32')

In [38]:
from numpy.random import randint

In [39]:
randint(1,100)

19

# Numpy Array Indexing and Selection

In [40]:
import numpy as np

In [41]:
arr = np.arange(0,11)

In [42]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
arr[8]

8

In [44]:
arr[0]

0

In [45]:
arr[1:5]

array([1, 2, 3, 4])

In [46]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [47]:
arr[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [49]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [50]:
arr = np.arange(0,11)

In [51]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [53]:
slice_of_arr[:]

array([0, 1, 2, 3, 4, 5])

In [54]:
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [55]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [56]:
# Here is an important point to note
# slice_of_arr did not make a copy instead it changed the original array itself.
# Numpy avoid making copies of the array implicitly in order to avoid space issues.

In [57]:
# To make a copy specifically indicate:
arr_copy = arr.copy()

In [58]:
arr_copy[0:6] = 50

In [59]:
arr_copy

array([50, 50, 50, 50, 50, 50,  6,  7,  8,  9, 10])

In [60]:
arr
# Unchanged array. same as previous

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

# 2D Array

In [61]:
import numpy as np

In [62]:
arr_2d = np.array([[10,20,30],[40,50,60],[70,80,90]])
arr_2d
# Double bracket shown below shows 2 dimentional array

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [63]:
# element "10"
arr_2d[0][0]

10

In [64]:
# first row 
arr_2d[0]

array([10, 20, 30])

In [65]:
# element "50"
arr_2d[1][1]

50

In [66]:
# element "80"
# Can also be grabbed by NOTATION
arr_2d[2,1]

80

In [67]:
arr_2d[1,2]

60

In [68]:
arr_2d

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [69]:
#grabbing values [20,30 and 50,60]
arr_2d[:2,1:]

array([[20, 30],
       [50, 60]])

In [70]:
# first 2 rows
arr_2d[:2]

array([[10, 20, 30],
       [40, 50, 60]])

In [71]:
#grabbing rows 2nd and 3rd (values [40,50,60 and 70,80,90])
arr_2d[1:,0:]

array([[40, 50, 60],
       [70, 80, 90]])

In [72]:
#grabbing column 1st 
arr_2d[0:,0:1]

array([[10],
       [40],
       [70]])

In [73]:
#grabbing column 3rd 
arr_2d[0:,2:]

array([[30],
       [60],
       [90]])

In [74]:
#grabbing column 3rd in Array display
arr_2d[0:,2]

array([30, 60, 90])

# Conditional Selection


In [75]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [76]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [77]:
bool_arr = arr > 5

In [78]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [79]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [80]:
arr[arr<3]

array([1, 2])

# Exercise

In [81]:
arr_2D = np.arange(50).reshape(5,10)
arr_2D

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [82]:
arr_2D[1:3,3:5]

array([[13, 14],
       [23, 24]])

# Numpy Operations
- Array with Array
- Array with Scalars
- Universal Array Functions(UAF)

In [83]:
import numpy as np

In [84]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [85]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [86]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [87]:
arr * arr
# creating square 

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [88]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [89]:
arr / arr
# Numpy provides a error warning

<ipython-input-89-5224550c353c>:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [90]:
1 / arr
# Numpy provides a error warning = infinity(inf)

<ipython-input-90-e0a14256bfcd>:1: RuntimeWarning: divide by zero encountered in true_divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [91]:
arr ** 2
# array exponential 

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [92]:
arr ** 3

array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000],
      dtype=int32)

In [93]:
# UAF
# square root
arr ** (1/2)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [94]:
# Same as above
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [95]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [96]:
np.max(arr)

10

In [97]:
arr.max()

10

In [98]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [99]:
np.cos(arr)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026,
       -0.83907153])

In [100]:
np.log(arr)

<ipython-input-100-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [101]:
np.power(arr,2)

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

# ---- NumPy Exercises ----

#### completed in Jupyter notebook exercise 