In [1]:
my_list = [1,2,3,4]

In [2]:
import numpy as np

In [3]:
np.array([my_list])

array([[1, 2, 3, 4]])

In [4]:
arr = np.array([my_list])

In [5]:
arr

array([[1, 2, 3, 4]])

# 2-D matrix

In [7]:
my_matrices = [[1,2,3],[4,5,6],[7,8,9]]

In [8]:
my_matrices

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
np.array(my_matrices)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Range and Arange

In [10]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
np.zeros(3)

In [ ]:
np.zeros((3,3))

In [ ]:
np.zeros((2,3))

In [ ]:
np.ones(3)

In [12]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.ones((3))

array([1., 1., 1.])

In [14]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [ ]:
np.eye(4)

In [15]:
np.random.rand(5)

array([0.86460294, 0.25155712, 0.14773534, 0.52354982, 0.66091   ])

In [16]:
np.random.rand(5,5)

array([[0.76002954, 0.83349741, 0.62001558, 0.31195648, 0.22138425],
       [0.07992443, 0.87122237, 0.20782127, 0.77002063, 0.11482169],
       [0.90745127, 0.88225758, 0.62384561, 0.46470236, 0.93021269],
       [0.77982528, 0.64857875, 0.77469485, 0.61814393, 0.24733619],
       [0.36757907, 0.12066103, 0.70454094, 0.25579442, 0.48670502]])

In [17]:
np.random.randn(2)

array([-0.92912951,  1.53472265])

In [18]:
np.random.randn(2,2)

array([[ 1.48699179, -1.1019674 ],
       [ 1.1180311 ,  0.42790007]])

# Random Integer Range

In [19]:
np.random.randint(0,100,10)

array([58, 46, 65, 36, 83, 61, 85, 98, 12, 30])

# Methods in Array

In [23]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [22]:
rand_arr = np.random.randint(0,50,10)
rand_arr

array([47, 15, 16, 20, 15, 28, 46, 27, 39, 18])

In [24]:
arr.reshape(5,5)
# It will give error if you can't fill up matrix correctly.

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

# other methods

In [ ]:
rand_arr

In [ ]:
# max min values will be as per the random array values

In [ ]:
rand_arr.max()

In [ ]:
rand_arr.min()

In [ ]:
rand_arr.argmax()
# This will give max values "index"

In [ ]:
rand_arr.argmin()

In [ ]:
arr.shape

In [ ]:
arr = arr.reshape(5,5)
arr

In [ ]:
# Now
arr.shape

In [ ]:
arr.dtype

In [ ]:
rand_arr.dtype

In [ ]:
from numpy.random import randint

In [ ]:
randint(1,100)

# Numpy Array Indexing and Selection

In [25]:
import numpy as np

In [26]:
arr = np.arange(0,11)

In [ ]:
arr

In [27]:
arr[8]

8

In [28]:
arr[0]

0

In [29]:
arr[1:5]

array([1, 2, 3, 4])

In [30]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [31]:
arr[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [33]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [34]:
arr = np.arange(0,11)

In [35]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [37]:
slice_of_arr[:]

array([0, 1, 2, 3, 4, 5])

In [38]:
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [39]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [ ]:
# Here is an important point to note
# slice_of_arr did not make a copy instead it changed the original array itself.
# Numpy avoid making copies of the array implicitly in order to avoid space issues.

In [ ]:
# To make a copy specifically indicate:
arr_copy = arr.copy()

In [ ]:
arr_copy[0:6] = 50

In [ ]:
arr_copy

In [ ]:
arr
# Unchanged array. same as previous

# 2D Array

In [ ]:
import numpy as np

In [21]:
arr_2d = np.array([[10,20,30],[40,50,60],[70,80,90]])
arr_2d
# Double bracket shown below shows 2 dimentional array

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [ ]:
# element "10"
arr_2d[0][0]

In [ ]:
# first row 
arr_2d[0]

In [ ]:
# element "50"
arr_2d[1][1]

In [ ]:
# element "80"
# Can also be grabbed by NOTATION
arr_2d[2,1]

In [ ]:
arr_2d[1,2]

In [ ]:
arr_2d

In [ ]:
#grabbing values [20,30 and 50,60]
arr_2d[:2,1:]

In [ ]:
# first 2 rows
arr_2d[:2]

In [ ]:
#grabbing rows 2nd and 3rd (values [40,50,60 and 70,80,90])
arr_2d[1:,0:]

In [ ]:
#grabbing column 1st 
arr_2d[0:,0:1]

In [ ]:
#grabbing column 3rd 
arr_2d[0:,2:]

In [ ]:
#grabbing column 3rd in Array display
arr_2d[0:,2]

# Conditional Selection


In [ ]:
arr = np.arange(1,11)
arr

In [ ]:
arr > 5

In [ ]:
bool_arr = arr > 5

In [ ]:
bool_arr

In [ ]:
arr[arr>5]

In [ ]:
arr[arr<3]

# Exercise

In [ ]:
arr_2D = np.arange(50).reshape(5,10)
arr_2D

In [ ]:
arr_2D[1:3,3:5]

# Numpy Operations
- Array with Array
- Array with Scalars
- Universal Array Functions(UAF)

In [ ]:
import numpy as np

In [ ]:
arr = np.arange(0,11)
arr

In [ ]:
arr + arr

In [ ]:
arr - arr

In [ ]:
arr * arr
# creating square 

In [ ]:
arr + 100

In [ ]:
arr / arr
# Numpy provides a error warning

In [ ]:
1 / arr
# Numpy provides a error warning = infinity(inf)

In [ ]:
arr ** 2
# array exponential 

In [ ]:
arr ** 3

In [ ]:
# UAF
# square root
arr ** (1/2)

In [ ]:
# Same as above
np.sqrt(arr)

In [ ]:
np.exp(arr)

In [ ]:
np.max(arr)

In [ ]:
arr.max()

In [ ]:
np.sin(arr)

In [ ]:
np.cos(arr)

In [ ]:
np.log(arr)

In [ ]:
np.power(arr,2)

# ---- NumPy Exercises ----

#### completed in Jupyter notebook exercise 